name: Python application

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10 and PipEnv
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip |
        pip install --user pipenv |
        pipenv install
    - name: Lint with flake8
      run: |
        pipenv run flake8 |
        pipenv run lint
    - name: Test with pytest
      run: |
        pipenv run pytest
